application: tufilmoteca
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /descarga
  script: controller/descarga.py
- url: /descargacuevana
  script: controller/descargacuevana.py
- url: /
  script: controller/index.py
- url: /peliculas
  script: controller/peliculas.py
- url: /(?P<tipo>\w+)/(?P<numid>\d+)
  script: controller/verfuentes.py
- url: /genero/peliculas/(?P<genero>\w+)
  script: controller/genero.py
- url: /busqueda
  script: controller/busqueda.py

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on
